variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

buildHugo:
  stage: build
  image: "jojomi/hugo"
  script:
    - hugo -s hugo_site
  artifacts:
    paths: 
      - hugo_site/public/

deployS3:
  stage: deploy
  image: "registry.gitlab.com/twaluigi/tomwygonik.com/awscli:latest"
  dependencies: 
    - buildHugo
  script:
    - export CREDS=$(aws sts assume-role --role-arn ${ROLE_ARN} --role-session-name "gitlab-$(date +%Y%m%d%H%M%S)" | jq -r '.Credentials')
    - export AWS_ACCESS_KEY_ID=$(echo ${CREDS} | jq -r '.AccessKeyId')
    - export AWS_SECRET_ACCESS_KEY=$(echo ${CREDS} | jq -r '.SecretAccessKey')
    - export AWS_SESSION_TOKEN=$(echo ${CREDS} | jq -r '.SessionToken')
    - aws s3 sync --delete hugo_site/public/ s3://${BUCKET_NAME}/
