# Site settings
title: "Thomas Wygonik"
email: thomas.wygonik@gmail.com
description: "Thomas Wygonik's website and projects"
baseurl: ""
url: ""
title_description: "I’m a jack of all trades in IT. I have experience in networking, systems adminstration, and cloud computing. My current job combines all of these aspects. This site is a collection of my random projects."
title_image: "https://www.gravatar.com/avatar/28309b7ab26f245ed1e9df632db0266b"
google_analytics: 
github_repository: https://github.com/twaluigi
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  twaluigi
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Theme made by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
