version: 0.2

phases:
  pre_build:
    commands:
      - export LC_ALL="C.UTF-8"
      - export LANG="en_US.UTF-8"
      - export LANGUAGE="en_US.UTF-8"
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 *******"
      - aws s3 sync --delete --exclude "buildspec.yml" --exclude "README.md" --exclude "LICENSE" _site/ s3://$SITE_NAME
