version: 0.2
   
phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 *******"
      - aws s3 sync --delete --exclude "buildspec.yml" --exclude "README.md" --exclude "LICENSE" _site/ s3://thomaswygonik.com
