version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist bundler
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - bundle exec jekyll build
