baseURL = "https://tomwygonik.com"
languageCode = "en-us"
title = "Tom Wygonik"
theme = "tale"
[Author]
    name = "Tom Wygonik"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        title = "Posts"
        url = "/posts/"
        weight = 0
